/**
 * SII Section to PDF Page Mapping
 * Maps section references (e.g., "5.1") to specific page numbers in SII PDFs
 *
 * This mapping is built manually or can be auto-generated by analyzing PDF structure.
 * For now, we use a best-guess based on typical SII document structure.
 */

export interface SectionPageMapping {
  [section: string]: number;
}

/**
 * Page mappings for each SII document
 * Key: document number (1-15)
 * Value: mapping of section strings to page numbers
 */
export const SII_PAGE_MAPPINGS: Record<number, SectionPageMapping> = {
  // Doc 11: Service crane (yearly)
  11: {
    "5": 6,      // Section 5 starts on page 6
    "5.1": 6,    // Section 5.1 - To examine the service crane
    "5.1.1": 6,  // Section 5.1.1 - To do a check of the electric chain hoist
  },

  // Doc 6: Gearbox and gear oil system
  6: {
    "5": 6,
    "5.2": 7,
    "5.2.1": 8,
    "5.2.2": 9,
    "5.2.3": 10,
    "5.2.4": 11,
    "5.2.8": 15,
    "5.2.9": 16,
    "5.2.10": 17,
    "5.2.11": 18,
    "5.2.12": 19,
    "5.2.13": 20,
    "5.3": 21,
    "6.2.6": 25,
    "6.2.7": 26,
  },

  // Doc 9: Nacelle
  9: {
    "5": 6,
    "5.1": 7,
    "5.1.4": 10,
    "5.2": 15,
    "5.2.1": 16,
    "5.2.3": 18,
    "5.4": 20,
    "5.5": 21,
    "5.5.1": 22,
  },

  // Doc 5: Hydraulic systems
  5: {
    "5": 6,
    "5.1": 7,
    "5.1.1": 8,
    "5.1.2": 9,
    "5.1.3": 10,
    "5.1.4": 11,
    "5.1.5": 12,
    "5.1.6": 13,
    "5.2": 14,
    "5.3": 15,
  },

  // Doc 4: Hub and blades
  4: {
    "5": 6,
    "5.1": 7,
    "5.1.1": 8,
    "5.1.2": 10,
    "5.1.3": 12,
    "5.1.5": 14,
    "5.1.6": 15,
    "5.1.7": 16,
    "5.1.8": 17,
    "5.2": 18,
    "5.2.1": 19,
    "5.2.2": 20,
    "5.2.5": 23,
    "5.2.7": 25,
  },

  // Add more mappings for other documents as needed
  // These can be built incrementally or auto-generated
};

/**
 * Gets the page number for a specific section in a document
 * Falls back to page 1 if no mapping exists
 *
 * @param documentNumber - The SII document number (1-15)
 * @param section - The section reference (e.g., "5.1", "5.2.3")
 * @returns Page number to jump to
 */
export function getSectionPage(documentNumber: number, section: string): number {
  const mapping = SII_PAGE_MAPPINGS[documentNumber];
  if (!mapping) {
    return 1; // Default to first page if no mapping
  }

  // Try exact match first
  if (mapping[section]) {
    return mapping[section];
  }

  // Try parent sections (e.g., "5.2.3" -> "5.2" -> "5")
  const parts = section.split('.');
  for (let i = parts.length - 1; i > 0; i--) {
    const parentSection = parts.slice(0, i).join('.');
    if (mapping[parentSection]) {
      return mapping[parentSection];
    }
  }

  // Default to first content page (usually page 6 after covers/TOC)
  return 6;
}

/**
 * Checks if a mapping exists for a document
 */
export function hasSectionMapping(documentNumber: number): boolean {
  return documentNumber in SII_PAGE_MAPPINGS;
}
